# Generated by Django 5.1.1 on 2025-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='U', max_length=50, verbose_name='Роль'),
        ),
    ]
